Добавляет функции getRandomPositiveInteger и getRandomGeographicCoord…
htmlacademy-javascript/2122221-keksobooking-27 pull request #2
Opened 2022-09-29 21:05 UTC by annvolfers

…inate

2022-09-30 04:55 UTC, Dima-Dim commented on js/main.js
> +  return +(Math.random() * (max - min) + min).toFixed(decimals);
Что за `+` перед скобками? :)

2022-09-30 07:49 UTC, annvolfers commented on js/main.js
> +  return +(Math.random() * (max - min) + min).toFixed(decimals);
приведение возвращаемой методом toFixed строки к числу

2022-10-01 08:59 UTC, Dima-Dim commented on js/main.js
> +  return +(Math.random() * (max - min) + min).toFixed(decimals);
А почему не Nimber() для этого используется?

2022-10-01 09:38 UTC, Dima-Dim requested changes

2022-10-01 09:38 UTC, Dima-Dim commented on js/main.js
> +    min = max;
Не нужно переопределять перепенные переданные в функции, там можно очень легко запутать себя, когда придётся разбираться с ошибками.

2022-10-01 12:02 UTC, annvolfers commented on js/main.js
> +  return +(Math.random() * (max - min) + min).toFixed(decimals);
так короче) но наверное менее читабельно. лучше использовать number()?

2022-10-01 12:48 UTC, annvolfers commented on js/main.js
> +    min = max;
поправила

2022-10-01 12:48 UTC, annvolfers commented on js/main.js
> +  return +(Math.random() * (max - min) + min).toFixed(decimals);
и это поправила

2022-10-02 08:58 UTC, Dima-Dim commented on js/main.js
> +  return +(Math.random() * (max - min) + min).toFixed(decimals);
> так короче) но наверное менее читабельно. лучше использовать number()?

Да, лучше читать более однозначный код.

2022-10-02 13:30 UTC, merged