Добавляет создание массива из сгенерированных объектов с описанием об…
htmlacademy-javascript/2122221-keksobooking-27 pull request #3
Opened 2022-10-02 17:32 UTC by annvolfers

…ъявлений

2022-10-03 11:35 UTC, Dima-Dim requested changes

2022-10-03 11:35 UTC, Dima-Dim commented on js/main.js
> +  const locationLat = getRandomGeographicCoordinate(35.65, 35.7, 5);
`35.65, 35.7, 5` это магические значения.
https://up.htmlacademy.ru/javascript/27/criteries#d19

2022-10-03 11:35 UTC, Dima-Dim commented on js/main.js
> +// eslint-disable-next-line no-unused-vars
Лучше вывести в консоль, чтобы можно было проверить как оно работает.

2022-10-03 11:51 UTC, annvolfers commented on js/main.js
> +// eslint-disable-next-line no-unused-vars
готово

2022-10-03 11:51 UTC, annvolfers commented on js/main.js
> +  const locationLat = getRandomGeographicCoordinate(35.65, 35.7, 5);
поправила

2022-10-04 08:24 UTC, Dima-Dim commented on js/main.js
> +  const photosArray = [];
Тут тоже `Array` лишнее.

2022-10-04 08:24 UTC, Dima-Dim commented on js/main.js
> +function createPhotosArray(arrayLength) {
Часть `Array` лишняя.

2022-10-04 08:24 UTC, merged

2022-10-04 09:13 UTC, annvolfers commented on js/main.js
> +  const photosArray = [];
спасибо, поправлю